spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=false
spring.datasource.username=postgres.wqfopponhofwbehteijq
spring.datasource.password=nHvWaBPbHG0yaAzO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI disponible en /swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Puerto del servidor
server.port=8080

